import {
  boolean,
  integer,
  jsonb,
  text,
  timestamp,
} from 'drizzle-orm/pg-core';
import { appPgTable } from './table.js';

export const services = appPgTable('services', {
  id: text('id').primaryKey(),
  title: text('title').notNull(),
  slug: text('slug').notNull().default(''),
  category: text('category').notNull().default('home-healthcare'),
  subcategory: text('subcategory').notNull().default(''),
  status: text('status').notNull().default('active'),
  active: boolean('active').notNull().default(true),
  price: integer('price').notNull().default(0),
  originalPrice: integer('original_price').notNull().default(0),
  salePrice: integer('sale_price').notNull().default(0),
  currency: text('currency').notNull().default('AED'),
  homeVisitFeeIncluded: boolean('home_visit_fee_included').notNull().default(true),
  duration: text('duration').notNull().default('1 Hour'),
  estimatedVisitTime: text('estimated_visit_time').notNull().default(''),
  image: text('image').notNull(),
  shortDescription: text('short_description').notNull().default(''),
  fullDescription: text('full_description').notNull().default(''),
  description: text('description').notNull().default(''),
  inclusions: jsonb('inclusions').notNull().default([]),
  preparationInstructions: text('preparation_instructions').notNull().default(''),
  whoIsItFor: text('who_is_it_for').notNull().default(''),
  serviceLocation: text('service_location').notNull().default('at-home'),
  availability: text('availability').notNull().default(''),
  tags: jsonb('tags').notNull().default([]),
  displayPriority: integer('display_priority').notNull().default(100),
  seoTitle: text('seo_title').notNull().default(''),
  seoDescription: text('seo_description').notNull().default(''),
  popular: boolean('popular').notNull().default(false),
  enquiryOnly: boolean('enquiry_only').notNull().default(false),
  attributes: jsonb('attributes').notNull().default([]),
  vendorPrices: jsonb('vendor_prices').notNull().default([]),
  bookingNotice: text('booking_notice').notNull().default(''),
  remarks: text('remarks').notNull().default(''),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});
