export const HOME_HEALTHCARE_CATEGORIES = [
  {
    id: 'cat-home-health',
    title: 'Nursing care at Home',
    image: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&q=80&w=400',
    slug: 'home-healthcare',
    description: 'Nurses providing premium in-home clinical care, wound antiseptic dressing, and support.',
  },
];

export const HOME_HEALTHCARE_SERVICES = [
  {
    id: 'srv-generic-nurse',
    title: 'Generic Nurse Visit',
    category: 'home-healthcare',
    price: 250,
    duration: '1 Hour (Min 3 hrs)',
    image: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&q=80&w=400',
    description: 'Expert nursing support brought to you - routine care, recovery assistance, and health monitoring, all in one visit.',
    popular: true,
    bookingNotice: '12 hours prior booking',
  },
  {
    id: 'srv-wound-small',
    title: 'Wound Care and Surgical Dressing - Small',
    category: 'home-healthcare',
    price: 500,
    duration: '1 Session',
    image: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&q=80&w=400',
    description: 'Precise, hygienic care for minor wounds and small surgical sites - cleaned, dressed, and monitored by a trained nurse to support faster healing and prevent infection.',
    popular: false,
    bookingNotice: '12 hours prior booking',
  },
  {
    id: 'srv-wound-medium',
    title: 'Wound Care and Surgical Dressing - Medium',
    category: 'home-healthcare',
    price: 650,
    duration: '1 Session',
    image: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&q=80&w=400',
    description: 'Precise, hygienic care for minor wounds and medium surgical sites - cleaned, dressed, and monitored by a trained nurse to support faster healing and prevent infection.',
    popular: false,
    bookingNotice: '12 hours prior booking',
  },
  {
    id: 'srv-wound-large',
    title: 'Wound Care and Surgical Dressing - Large',
    category: 'home-healthcare',
    price: 1000,
    duration: '1 Session',
    image: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&q=80&w=400',
    description: 'Precise, hygienic care for minor wounds and large surgical sites - cleaned, dressed, and monitored by a trained nurse to support faster healing and prevent infection.',
    popular: false,
    bookingNotice: '12 hours prior booking',
  },
  {
    id: 'srv-catheterisation-female',
    title: 'Catheterisation at Home (Female)',
    category: 'home-healthcare',
    price: 850,
    duration: '1 Session',
    image: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&q=80&w=400',
    description: 'Safe, sterile catheter insertion and care delivered in the comfort of your home - performed by a trained clinical nurse with full privacy, dignity, and clinical precision.',
    popular: false,
    bookingNotice: '12 hours prior booking',
  },
  {
    id: 'srv-iv-antibiotics-prescription',
    title: 'IV antibiotics at Home (with Dr Prescription)',
    category: 'home-healthcare',
    price: 750,
    duration: '1 Session',
    image: 'https://images.unsplash.com/photo-1513224502586-d1e602410265?auto=format&fit=crop&q=80&w=400',
    description: 'Complete your antibiotic course from the comfort of home - a qualified nurse administers your prescribed IV treatment safely and efficiently, so you recover without the hospital stay.',
    popular: false,
    bookingNotice: '12 hours prior booking',
  },
];
