<?php

namespace Database\Seeders;

use App\Models\Service;
use App\Models\Vendor;
use App\Models\VendorServiceAssignment;
use App\Support\SequentialId;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class BiomarkerSeeder extends Seeder
{
    public function run(): void
    {
        $demoVendor = Vendor::firstOrCreate(
            ['email' => 'vendor@medzivahealthcare.com'],
            ['id' => 'v-demo', 'name' => 'Demo Vendor', 'type' => 'Healthcare Provider', 'address' => 'Dubai', 'active' => true]
        );

        $biomarkers = [
            ['code' => 'T1339', 'name' => '17-Hydroxy Progesterone', 'price' => 140],
            ['code' => 'T1104', 'name' => 'Activated Partial Thromboplastin Time (APTT)', 'price' => 35],
            ['code' => 'T1022', 'name' => 'Alanine Aminotransferase  (ALT / GPT)', 'price' => 30],
            ['code' => 'T1025', 'name' => 'Albumin', 'price' => 25],
            ['code' => 'T1364', 'name' => 'Albumin/Globulin Ratio (A/G Ratio)', 'price' => 70],
            ['code' => 'T1020', 'name' => 'Alkaline Phosphatase', 'price' => 30],
            ['code' => 'T3866', 'name' => 'Alpha 2 Macroglobulin', 'price' => 75],
            ['code' => 'T1060', 'name' => 'Alpha Fetoprotein (AFP)', 'price' => 75],
            ['code' => 'T1028', 'name' => 'Amylase - Total', 'price' => 30],
            ['code' => 'T1160', 'name' => 'Amylase - Total (24 Hour Urine)', 'price' => 35],
            ['code' => 'T1713', 'name' => 'Amylase - Total (Random Urine)', 'price' => 35],
            ['code' => 'T1877', 'name' => 'Anti-Mullerian Hormone', 'price' => 160],
            ['code' => 'T3004', 'name' => 'Anti-Thyroglobulin Antibodies (aTg)', 'price' => 85],
            ['code' => 'T3003', 'name' => 'Anti-Thyroid Microsomal Antibodies (aTPO)', 'price' => 85],
            ['code' => 'T1037', 'name' => 'Apolipoprotein A1', 'price' => 40],
            ['code' => 'T1038', 'name' => 'Apolipoprotein B', 'price' => 40],
            ['code' => 'T1042', 'name' => 'Aspartate Aminotransferase (AST / GOT)', 'price' => 30],
            ['code' => 'T1061', 'name' => 'Beta 2 - Microglobulin', 'price' => 75],
            ['code' => 'T1605', 'name' => 'Beta Human Chorionic Gonadotropin (BhCG)', 'price' => 65],
            ['code' => 'T1367', 'name' => 'Bicarbonate (HCO3)', 'price' => 30],
            ['code' => 'T1245', 'name' => 'Bile Acids - Total', 'price' => 90],
            ['code' => 'T4222', 'name' => 'Bilharziasis Stool', 'price' => 25],
            ['code' => 'T4223', 'name' => 'Bilharziasis Urine', 'price' => 25],
            ['code' => 'T1019', 'name' => 'Bilirubin - Direct', 'price' => 25],
            ['code' => 'T1699', 'name' => 'Bilirubin - Indirect', 'price' => 25],
            ['code' => 'T1018', 'name' => 'Bilirubin - Total', 'price' => 25],
            ['code' => 'T1579', 'name' => 'Bilirubin (Random Urine)', 'price' => 30],
            ['code' => 'T1354', 'name' => 'Blood Film (Peripheral Smear )', 'price' => 30],
            ['code' => 'T1594', 'name' => 'Blood Group-Rh (ABO-Rh)', 'price' => 20],
            ['code' => 'T1457', 'name' => 'Brucella Antibodies', 'price' => 55],
            ['code' => 'T1344', 'name' => 'Calcitonin', 'price' => 180],
            ['code' => 'T1032', 'name' => 'Calcium', 'price' => 30],
            ['code' => 'T1869', 'name' => 'Calcium - Ionized (Free)', 'price' => 100],
            ['code' => 'T1580', 'name' => 'Calcium (24 Hour Urine)', 'price' => 30],
            ['code' => 'T1716', 'name' => 'Calcium (Random Urine )', 'price' => 30],
            ['code' => 'T4282', 'name' => 'Calcium/Creatinine (24 Hour Urine)  Ratio', 'price' => 60],
            ['code' => 'T3048', 'name' => 'Calcium/Creatinine Ratio Urine Spot', 'price' => 45],
            ['code' => 'T3221', 'name' => 'Calprotectin (screening) (stool)', 'price' => 175],
            ['code' => 'T1056', 'name' => 'Cancer Antigen (CA 125) - Ovarian', 'price' => 130],
            ['code' => 'T1058', 'name' => 'Cancer Antigen (CA 15.3) - Breast', 'price' => 130],
            ['code' => 'T1057', 'name' => 'Cancer Antigen (CA 19.9) - Pancreatic', 'price' => 130],
            ['code' => 'T1345', 'name' => 'Carcino Embryonic Antigen (CEA)', 'price' => 90],
            ['code' => 'T3023', 'name' => 'Cardiolipin Antibody, IgG', 'price' => 100],
            ['code' => 'T2764', 'name' => 'Cardiolipin Antibody, IgM', 'price' => 100],
            ['code' => 'T1255', 'name' => 'Ceruloplasmin', 'price' => 50],
            ['code' => 'T1941', 'name' => 'Chlamydia trachomatis Antigen', 'price' => 130],
            ['code' => 'T1422', 'name' => 'Chlamydia Trachomatis Antigen (PCR)', 'price' => 100],
            ['code' => 'T2786', 'name' => 'Chlamydia trachomatis, IgG', 'price' => 75],
            ['code' => 'T2797', 'name' => 'Chlamydia trachomatis, IgM', 'price' => 75],
            ['code' => 'T1012', 'name' => 'Chloride', 'price' => 25],
            ['code' => 'T1582', 'name' => 'Chloride (Cl) (24 Hour Urine)', 'price' => 25],
            ['code' => 'T1717', 'name' => 'Chloride (Cl) (Urine)', 'price' => 25],
            ['code' => 'T1036', 'name' => 'Cholesterol - LDL (Direct)', 'price' => 25],
            ['code' => 'T1370', 'name' => 'Cholesterol', 'price' => 25],
            ['code' => 'T1035', 'name' => 'Cholesterol-HDL', 'price' => 35],
            ['code' => 'T1461', 'name' => 'Complement - C3', 'price' => 65],
            ['code' => 'T1462', 'name' => 'Complement - C4', 'price' => 65],
            ['code' => 'T3009', 'name' => 'Complete Blood Count (CBC) with differential', 'price' => 55],
            ['code' => 'L1004', 'name' => 'Comprehensive Respiratory Pathogen Panel-25, RT PCR (Influenza A virus, Influenza H1N1, Influenza H3N2, Respiratory syncytial virus A, Respiratory syncytial virus B, Pandemic H1N1/09 virus, Influenza B virus, Parainfluenza virus 1, Parainfluenza virus 2, Parainfluenza virus 3, Parainfluenza virus 4, Metapneumovirus, Enterovirus, Coronavirus 229E, Bocavirus, Coronavirus OC43, Coronavirus NL63, Adenovirus, Rhinovirus A/B/C, Streptococcus pneumoniae, Chlamydia pneumoniae, Legionella pneumophila, Haemophilus influenzae, Mycoplasma pneumoniae, Bordetella pertussis)', 'price' => 1100],
            ['code' => 'T1089', 'name' => 'Coomb’s Test - Direct', 'price' => 30],
            ['code' => 'T1090', 'name' => 'Coomb’s Test - Indirect (Titer)', 'price' => 50],
            ['code' => 'T1262', 'name' => 'Copper', 'price' => 50],
            ['code' => 'T1119', 'name' => 'Cortisol - Total (AM)', 'price' => 75],
            ['code' => 'T1878', 'name' => 'Cortisol - Total (PM)', 'price' => 75],
            ['code' => 'T2854', 'name' => 'Cortisol - Total (Random)', 'price' => 75],
            ['code' => 'T1416', 'name' => 'Cortisol Free (24 hours Urine)', 'price' => 80],
            ['code' => 'T4241', 'name' => 'Cortisol Free (Random Urine)', 'price' => 80],
            ['code' => 'T4010', 'name' => 'C-Peptide Fasting', 'price' => 135],
            ['code' => 'T2767', 'name' => 'C-Peptide Random', 'price' => 135],
            ['code' => 'T1134', 'name' => 'C-Reactive Protein (CRP) - Quantitative', 'price' => 30],
            ['code' => 'T3219', 'name' => 'C-Reactive Protein Ultra Sensitive', 'price' => 55],
            ['code' => 'T1689', 'name' => 'Creatine Kinase - MB (CKMB)', 'price' => 45],
            ['code' => 'T1043', 'name' => 'Creatine Kinase (CPK / CK)', 'price' => 30],
            ['code' => 'T1978', 'name' => 'Creatinine', 'price' => 30],
            ['code' => 'T1397', 'name' => 'Creatinine (24 Hour Urine)', 'price' => 30],
            ['code' => 'T1714', 'name' => 'Creatinine (Random Urine)', 'price' => 30],
            ['code' => 'P0214', 'name' => 'Creatinine Clearance Test (24 hour Urine)--(Creatinine Serum, Creatinine Urine)', 'price' => 60],
            ['code' => 'P0044', 'name' => 'Creatinine Clearance Test', 'price' => 60],
            ['code' => 'T1754', 'name' => 'CSF - Chloride', 'price' => 25],
            ['code' => 'T1373', 'name' => 'CSF - Glucose', 'price' => 25],
            ['code' => 'T3087', 'name' => 'CSF - Total Leucocyte Count', 'price' => 50],
            ['code' => 'T1374', 'name' => 'CSF - Total Protein', 'price' => 35],
            ['code' => 'P0017', 'name' => 'Cytomegalovirus (CMV) Antibodies, IgG + IgM--(Cytomegalovirus IgG & IgM Antibodies)', 'price' => 140],
            ['code' => 'T2755', 'name' => 'Cytomegalovirus (CMV) Antibody, IgG', 'price' => 65],
            ['code' => 'T2756', 'name' => 'Cytomegalovirus (CMV) Antibody, IgM', 'price' => 85],
            ['code' => 'T2878', 'name' => 'D - Dimer', 'price' => 90],
            ['code' => 'T1121', 'name' => 'Dehydroepiandrosterone - Sulfate (DHEA-S)', 'price' => 95],
            ['code' => 'L0104', 'name' => 'Dengue IgM antibody', 'price' => 75],
            ['code' => 'T1355', 'name' => 'Down risk Estimation', 'price' => 283],
            ['code' => 'T3423', 'name' => 'EBV IgG Panel', 'price' => 105],
            ['code' => 'T3422', 'name' => 'EBV IgM Panel', 'price' => 120],
            ['code' => 'P0332', 'name' => 'Epstein-Barr Virus (EBV) Antibodies, IgG+ IgM --(Epstein Barr Virus IgG & IgM Antibodies)', 'price' => 175],
            ['code' => 'T1478', 'name' => 'Endomysium Antibody, IgA', 'price' => 100],
            ['code' => 'T3158', 'name' => 'Endomysium, IgG', 'price' => 125],
            ['code' => 'T1097', 'name' => 'Erythrocyte Sedimentation Rate (ESR)', 'price' => 15],
            ['code' => 'T3321', 'name' => 'Estimated Average Glucose (AEG)', 'price' => 65],
            ['code' => 'T1116', 'name' => 'Estradiol (E2)', 'price' => 65],
            ['code' => 'T1358', 'name' => 'Estriol (E3', 'price' => 100],
            ['code' => 'T1189', 'name' => 'Factor V (Leiden) Mutation  (PCR)', 'price' => 250],
            ['code' => 'T1391', 'name' => 'Ferritin', 'price' => 115],
            ['code' => 'T1100', 'name' => 'Fibrinogen', 'price' => 70],
            ['code' => 'T1369', 'name' => 'Fluid Cell Count', 'price' => 55],
            ['code' => 'T1635', 'name' => 'Fluid Glucose', 'price' => 25],
            ['code' => 'T1726', 'name' => 'Fluid LDH', 'price' => 30],
            ['code' => 'T1751', 'name' => 'Fluid Uric Acid', 'price' => 25],
            ['code' => 'T1070', 'name' => 'Folate', 'price' => 85],
            ['code' => 'T1115', 'name' => 'Follicle Stimulating  Hormone (FSH)', 'price' => 65],
            ['code' => 'P0034', 'name' => 'Free Androgen Index--(Testosterone - Total, SHBG, FAI)', 'price' => 120],
            ['code' => 'T1023', 'name' => 'Gamma Glutamyl Transferase (GGT)', 'price' => 30],
            ['code' => 'T3134', 'name' => 'Gardnerella Vaginalis PCR', 'price' => 150],
            ['code' => 'T1486', 'name' => 'Gliadin Antibody, IgG', 'price' => 170],
            ['code' => 'T1026', 'name' => 'Globulin', 'price' => 20],
            ['code' => 'T3215', 'name' => 'Estimated GFR (eGFR)', 'price' => 35],
            ['code' => 'T1381', 'name' => 'Glucose - Fasting', 'price' => 25],
            ['code' => 'T1952', 'name' => 'Glucose - Post 75g Oral Glucose Load', 'price' => 30],
            ['code' => 'T1041', 'name' => 'Glucose - Postprandial', 'price' => 25],
            ['code' => 'T4208', 'name' => 'Glucose - Qualitative (Urine)', 'price' => 30],
            ['code' => 'T1016', 'name' => 'Glucose - Random', 'price' => 25],
            ['code' => 'T1158', 'name' => 'Glucose (24 Hour Urine)', 'price' => 50],
            ['code' => 'T1195', 'name' => 'Glucose-6-Phosphate Dehydrogenase (G6PD)- Quantitative', 'price' => 55],
            ['code' => 'T1382', 'name' => 'Glycosylated Haemoglobin (HbA1C)', 'price' => 65],
            ['code' => 'T1276', 'name' => 'Growth Hormone - After exercise', 'price' => 75],
            ['code' => 'T1401', 'name' => 'Growth Hormone - Fasting', 'price' => 75],
            ['code' => 'T2842', 'name' => 'Haemoglobin Variants Screen (HPLC)', 'price' => 195],
            ['code' => 'T1219', 'name' => 'Haptoglobin', 'price' => 60],
            ['code' => 'T1673', 'name' => 'Helicobacter pylori Antigen (Stool)', 'price' => 160],
            ['code' => 'T1140', 'name' => 'Helicobacter pylori IgG Abs', 'price' => 55],
            ['code' => 'P3950', 'name' => 'Hepatitis A (HAV), IgG+IgM -- (HAV IgG & IgM Antibodies)', 'price' => 140],
            ['code' => 'T3599', 'name' => 'Hepatitis A Virus (HAV), IgG', 'price' => 75],
            ['code' => 'T1663', 'name' => 'Hepatitis A Virus (HAV), IgM', 'price' => 85],
            ['code' => 'T1127', 'name' => 'Hepatitis B “c’’ Antibodies (HBc Total)', 'price' => 65],
            ['code' => 'T1126', 'name' => 'Hepatitis B “c” Antibody IgM (HBc IgM)', 'price' => 75],
            ['code' => 'T1129', 'name' => 'Hepatitis B “e” Antibody (Anti-HBe)', 'price' => 65],
            ['code' => 'T1128', 'name' => 'Hepatitis B “e” Antigen (HBe Ag)', 'price' => 65],
            ['code' => 'T1130', 'name' => 'Hepatitis B “s ” Antibody (Anti-HBs)', 'price' => 75],
            ['code' => 'T1675', 'name' => 'Hepatitis B “s” Ag (HBs Ag)', 'price' => 55],
            ['code' => 'P0006', 'name' => 'Hepatitis B Full Profile--(HBsAg, HBsAb, HBc IgM, HBc Ab, HBeAg, HBeAb)', 'price' => 345],
            ['code' => 'T1493', 'name' => 'Hepatitis B Virus - Qualitative (PCR)', 'price' => 400],
            ['code' => 'T1872', 'name' => 'Hepatitis B Virus - Quantitative (PCR)', 'price' => 420],
            ['code' => 'T3037', 'name' => 'Hepatitis C Virus (HCV) - Qualitative (PCR)', 'price' => 400],
            ['code' => 'T1495', 'name' => 'Hepatitis C Virus (HCV) - Quantitative (PCR)', 'price' => 420],
            ['code' => 'T1131', 'name' => 'Hepatitis C Virus (HCV) Antibodies', 'price' => 75],
            ['code' => 'L2099', 'name' => 'Hepatitis A,B, and C Screening Package IgG + IgM', 'price' => 290],
            ['code' => 'P0054', 'name' => 'Hepatitis Marker Screen--(HAV IgM, HBsAg, HCV Abs)', 'price' => 190],
            ['code' => 'P0039', 'name' => 'Herpes Simplex Full Profile--(Herpes Simplex-I & II,  IgG & IgM )', 'price' => 315],
            ['code' => 'T2757', 'name' => 'Herpes Simplex Virus (HSV)-I, IgG', 'price' => 85],
            ['code' => 'T2759', 'name' => 'Herpes Simplex Virus (HSV)-I, IgM', 'price' => 85],
            ['code' => 'T2760', 'name' => 'Herpes Simplex Virus (HSV)-II, IgM', 'price' => 85],
            ['code' => 'T2758', 'name' => 'Herpes Simplex Virus(HSV)-II, IgG', 'price' => 85],
            ['code' => 'T2766', 'name' => 'HIV Combi (Type 1 & 2 Antibodies+ p24 Antigen)', 'price' => 75],
            ['code' => 'L0708', 'name' => 'HIV-1 & 2 Qualitative (PCR)', 'price' => 400],
            ['code' => 'T1506', 'name' => 'HIV-1 Quantitative (PCR)', 'price' => 615],
            ['code' => 'T1511', 'name' => 'HLA Typing - B27 (PCR)', 'price' => 225],
            ['code' => 'L1172', 'name' => 'Homa Index', 'price' => 115],
            ['code' => 'T3647', 'name' => 'Homa Index Profile - Fasting (FBS, Insulin Fasting, Homa Index)', 'price' => 115],
            ['code' => 'T1392', 'name' => 'Homocysteine', 'price' => 210],
            ['code' => 'L0886', 'name' => 'HPV 25 Genotype Real Time PCR-Human Papilloma Virus Genotyping', 'price' => 188],
            ['code' => 'T4365', 'name' => 'HPV PCR (40 genotypes)', 'price' => 225],
            ['code' => 'T1515', 'name' => 'Immunoglobulin A (IgA)', 'price' => 55],
            ['code' => 'T1068', 'name' => 'Immunoglobulin E (IgE)', 'price' => 70],
            ['code' => 'T1517', 'name' => 'Immunoglobulin G (IgG)', 'price' => 55],
            ['code' => 'T1518', 'name' => 'Immunoglobulin M (IgM)', 'price' => 55],
            ['code' => 'P0007', 'name' => 'Immunoglobulin Panel--(IgG, IgM, IgA)', 'price' => 135],
            ['code' => 'T2722', 'name' => 'Immunohistochemical Stain', 'price' => 200],
            ['code' => 'L0682', 'name' => 'Infectious Disease Screening Panel 4, Qualitative, RT-PCR (Hepatitis B, Hepatitis C, HIV-1 & HIV-2)', 'price' => 500],
            ['code' => 'T4025', 'name' => 'Influenza Virus Type A  Antigen', 'price' => 150],
            ['code' => 'T4026', 'name' => 'Influenza Virus Type B Antigen', 'price' => 150],
            ['code' => 'P3879', 'name' => 'Influenza Virus Type A & B Antigen', 'price' => 150],
            ['code' => 'T2824', 'name' => 'Insulin - 1 Hour', 'price' => 90],
            ['code' => 'T2823', 'name' => 'Insulin - Fasting', 'price' => 90],
            ['code' => 'T1403', 'name' => 'Insulin - Like Growth Factor (IGF) - 1', 'price' => 200],
            ['code' => 'T1404', 'name' => 'Insulin - Like Growth Factor Binding Protein (IGFBP) -3', 'price' => 225],
            ['code' => 'T1405', 'name' => 'Insulin - Postprandial', 'price' => 90],
            ['code' => 'T2991', 'name' => 'Insulin - Random', 'price' => 90],
            ['code' => 'P0056', 'name' => 'Insulin Resistance Profile--(Insulin-Fasting, Insulin-1hr, Insulin 2hr)', 'price' => 215],
            ['code' => 'T1062', 'name' => 'Iron', 'price' => 35],
            ['code' => 'T1584', 'name' => 'Ketones (Random Urine)', 'price' => 25],
            ['code' => 'T1045', 'name' => 'Lactate Dehydrogenase (LDH)', 'price' => 35],
            ['code' => 'T1349', 'name' => 'Leishmania Smear', 'price' => 30],
            ['code' => 'T1029', 'name' => 'Lipase', 'price' => 50],
            ['code' => 'T1039', 'name' => 'Lipoprotein (a)', 'price' => 85],
            ['code' => 'P2731', 'name' => 'Liquid-Based Cytology + HPV PCR', 'price' => 325],
            ['code' => 'T1526', 'name' => 'Lupus Anticoagulants (LAC)', 'price' => 160],
            ['code' => 'T1114', 'name' => 'Luteinising Hormone (LH)', 'price' => 65],
            ['code' => 'T1027', 'name' => 'Magnesium', 'price' => 30],
            ['code' => 'T2868', 'name' => 'Magnesium (24 Hour Urine)', 'price' => 30],
            ['code' => 'T1755', 'name' => 'Malaria Smear', 'price' => 20],
            ['code' => 'T1529', 'name' => 'Measles, IgG', 'price' => 135],
            ['code' => 'T3075', 'name' => 'Measles, IgM', 'price' => 135],
            ['code' => 'T1387', 'name' => 'Microalbumin - Quantitative (24 Hour Urine)', 'price' => 65],
            ['code' => 'T1384', 'name' => 'Microalbumin - Quantitative (Random Urine)', 'price' => 65],
            ['code' => 'T2833', 'name' => 'Microalbumin/Creatinine Ratio (24 Hour Urine)--(Microalbumin, Creatinine Ratio)', 'price' => 100],
            ['code' => 'T4061', 'name' => 'Microalbumin/Creatinine Ratio (Random Urine)', 'price' => 100],
            ['code' => 'T1688', 'name' => 'Microfilaria Smear', 'price' => 60],
            ['code' => 'T1530', 'name' => 'Mitochondrial Antibody (AMA) Elisa', 'price' => 75],
            ['code' => 'L1530', 'name' => 'Mitochondrial Antibody by IF', 'price' => 75],
            ['code' => 'T1139', 'name' => 'Mono Spot Test (Infectious Mononucleosis)', 'price' => 35],
            ['code' => 'T3227', 'name' => 'Mumps IgG', 'price' => 135],
            ['code' => 'T3228', 'name' => 'Mumps IgM', 'price' => 150],
            ['code' => 'T2796', 'name' => 'Mycoplasma pneumoniae, IgG', 'price' => 105],
            ['code' => 'T2515', 'name' => 'Mycoplasma pneumoniae, IgM', 'price' => 105],
            ['code' => 'T1047', 'name' => 'Myoglobin - Quantitative', 'price' => 80],
            ['code' => 'T3100', 'name' => 'Neisseria gonorrhoeae (P.C.R)', 'price' => 100],
            ['code' => 'T1428', 'name' => 'Nuclear Antibodies (ANA Screen)', 'price' => 70],
            ['code' => 'T1644', 'name' => 'Occult Blood in Stool', 'price' => 25],
            ['code' => 'T1173', 'name' => 'Osmolality- Calculated (Blood)', 'price' => 60],
            ['code' => 'T1388', 'name' => 'Osmolality-Calculated (Random Urine)', 'price' => 60],
            ['code' => 'T1407', 'name' => 'Parathormone Hormone (PTH)', 'price' => 140],
            ['code' => 'T1076', 'name' => 'Phenytoin (Epanutin)', 'price' => 105],
            ['code' => 'P2789', 'name' => 'Phospholipid Antibodies (IgG & IgM)--(Phospholipid IgG & Phospholipid IgM)', 'price' => 125],
            ['code' => 'T2788', 'name' => 'Phospholipid Antibody, IgG', 'price' => 75],
            ['code' => 'T2790', 'name' => 'Phospholipid Antibody, IgM', 'price' => 75],
            ['code' => 'T2762', 'name' => 'Phosphorous', 'price' => 30],
            ['code' => 'T1585', 'name' => 'Phosphorous (24 Hour Urine)', 'price' => 35],
            ['code' => 'T1720', 'name' => 'Phosphorous (Random Urine)', 'price' => 35],
            ['code' => 'T1011', 'name' => 'Potassium (K)', 'price' => 25],
            ['code' => 'T1326', 'name' => 'Potassium (K) (24 Hour Urine)', 'price' => 30],
            ['code' => 'T1718', 'name' => 'Potassium (K) (Random Urine)', 'price' => 30],
            ['code' => 'T1946', 'name' => 'proBrain Natriuretic Peptide (proBNP)', 'price' => 265],
            ['code' => 'T3246', 'name' => 'Procalcitonin', 'price' => 225],
            ['code' => 'T1117', 'name' => 'Progesterone', 'price' => 65],
            ['code' => 'T1118', 'name' => 'Prolactin', 'price' => 65],
            ['code' => 'P0058', 'name' => 'Prostate Profile--(PSA-Total & PSA-Free)', 'price' => 130],
            ['code' => 'T1054', 'name' => 'Prostate Specific Antigen- Free (fPSA)', 'price' => 80],
            ['code' => 'T3476', 'name' => 'Prostatic Specific Antigen ratio', 'price' => 85],
            ['code' => 'T1053', 'name' => 'Prostatic Specific Antigen- Total (tPSA)', 'price' => 80],
            ['code' => 'T1024', 'name' => 'Protein- Total', 'price' => 25],
            ['code' => 'T1162', 'name' => 'Protein- Total (24 Hour Urine)', 'price' => 35],
            ['code' => 'T1721', 'name' => 'Protein- Total (Random Urine)', 'price' => 35],
            ['code' => 'T1725', 'name' => 'Protein Total- Ascitic Fluid', 'price' => 35],
            ['code' => 'T1586', 'name' => 'Protein/ Creatinine Ratio (24 Hour Urine)', 'price' => 65],
            ['code' => 'P0484', 'name' => 'Protein/ Creatinine Ratio (Random or 24 hrs Urine)--(Protein (Total), Creatinine)', 'price' => 65],
            ['code' => 'P3089', 'name' => 'Protein/ Creatinine Ratio (Random Urine)', 'price' => 65],
            ['code' => 'T1098', 'name' => 'Prothrombin Time (PT/INR)', 'price' => 30],
            ['code' => 'T4271', 'name' => 'Quantiferon – TB Gold Plus', 'price' => 400],
            ['code' => 'T1685', 'name' => 'Rapid Plasma Region (RPR) or VDRL - Screen', 'price' => 30],
            ['code' => 'T1395', 'name' => 'Reducing Substances (Stool)', 'price' => 40],
            ['code' => 'L2124', 'name' => 'Respiratory Pathogen Panel-8, RT PCR', 'price' => 250],
            ['code' => 'T3502', 'name' => 'Respiratory Syncytial Virus (RSV), Ag', 'price' => 90],
            ['code' => 'T1103', 'name' => 'Reticulocyte Count', 'price' => 20],
            ['code' => 'T1136', 'name' => 'Rheumatoid Factor (RF) - Titer', 'price' => 30],
            ['code' => 'T1648', 'name' => 'Rotavirus (Stool)', 'price' => 55],
            ['code' => 'P0014', 'name' => 'Rubella Antibodies, IgG + IgM--(Rubella IgG & IgM Antibodies)', 'price' => 145],
            ['code' => 'T1547', 'name' => 'Rubella Antibody, IgG', 'price' => 75],
            ['code' => 'T1548', 'name' => 'Rubella Antibody, IgM', 'price' => 105],
            ['code' => 'T1005', 'name' => 'Semen Analysis', 'price' => 55],
            ['code' => 'T1482', 'name' => 'Semen Fructose', 'price' => 55],
            ['code' => 'T1409', 'name' => 'Sex Hormone Binding Globulin (SHBG)', 'price' => 90],
            ['code' => 'L0164', 'name' => 'Smooth Muscle Antibodies by IF', 'price' => 75],
            ['code' => 'T1010', 'name' => 'Sodium (Na)', 'price' => 25],
            ['code' => 'T1152', 'name' => 'Sodium (Na) (24 Hour Urine)', 'price' => 25],
            ['code' => 'T1719', 'name' => 'Sodium (Na) (Random Urine)', 'price' => 25],
            ['code' => 'T1646', 'name' => 'Stool Analysis- Routine', 'price' => 25],
            ['code' => 'T1933', 'name' => 'Streptococcus Group A (RAPID TEST)', 'price' => 55],
            ['code' => 'T1314', 'name' => 'Tacrolimus (Prograf)', 'price' => 150],
            ['code' => 'T1616', 'name' => 'Tape Test for Pinworms', 'price' => 25],
            ['code' => 'T1363', 'name' => 'Testosterone- Free', 'price' => 150],
            ['code' => 'T1411', 'name' => 'Testosterone- Total', 'price' => 65],
            ['code' => 'T1412', 'name' => 'Thyroglobulin (Tg)', 'price' => 135],
            ['code' => 'T1112', 'name' => 'Thyroid  Stimulating Hormone (TSH)', 'price' => 65],
            ['code' => 'T1566', 'name' => 'Thyroid Stimulating Hormone (TSH) Receptor Antibodies', 'price' => 160],
            ['code' => 'T1111', 'name' => 'Thyroxine- Free (FT4)', 'price' => 65],
            ['code' => 'T1607', 'name' => 'Thyroxine- Total (TT4)', 'price' => 65],
            ['code' => 'T2711', 'name' => 'Total HCG', 'price' => 65],
            ['code' => 'T1063', 'name' => 'Total Iron Binding Capacity (TIBC)', 'price' => 45],
            ['code' => 'T1564', 'name' => 'Toxoplasma Antibodies, IgG', 'price' => 75],
            ['code' => 'P0015', 'name' => 'Toxoplasma Antibodies, IgG+IgM--(Toxoplasma IgG & IgM Antibodies)', 'price' => 140],
            ['code' => 'T1753', 'name' => 'Toxoplasma Antibodies, IgM', 'price' => 75],
            ['code' => 'T1315', 'name' => 'Transferrin', 'price' => 115],
            ['code' => 'P1064', 'name' => 'Transferrin Saturation--(Iron, TIBC)', 'price' => 150],
            ['code' => 'T2795', 'name' => 'Transglutaminase IgG', 'price' => 125],
            ['code' => 'T1359', 'name' => 'Transglutaminase, IgA', 'price' => 80],
            ['code' => 'T1683', 'name' => 'Treponema pallidum haemagglutination test (TPHA)', 'price' => 55],
            ['code' => 'T4157', 'name' => 'Treponema pallidum IgG', 'price' => 105],
            ['code' => 'T4158', 'name' => 'Treponema pallidum IgM', 'price' => 105],
            ['code' => 'T2831', 'name' => 'Trichomonas vaginalis (HVS)', 'price' => 60],
            ['code' => 'T1030', 'name' => 'Triglycerides', 'price' => 30],
            ['code' => 'T1113', 'name' => 'Tri-iodothyronine - Free (FT3)', 'price' => 65],
            ['code' => 'T1110', 'name' => 'Tri-iodothyronine - Total (TT3)', 'price' => 65],
            ['code' => 'T1072', 'name' => 'Troponin T (Quantitative)', 'price' => 85],
            ['code' => 'L0492', 'name' => 'Unsaturated Iron Binding Capacity(UIBC)', 'price' => 45],
            ['code' => 'T2746', 'name' => 'Urea', 'price' => 25],
            ['code' => 'T1587', 'name' => 'Urea (24 Hour Urine)', 'price' => 30],
            ['code' => 'T3043', 'name' => 'Urea (Random Urine)', 'price' => 30],
            ['code' => 'T1017', 'name' => 'Uric Acid', 'price' => 25],
            ['code' => 'T1156', 'name' => 'Uric Acid (24 Hour Urine)', 'price' => 30],
            ['code' => 'T1715', 'name' => 'Uric Acid (Random Urine)', 'price' => 30],
            ['code' => 'L0578', 'name' => 'Urinalysis (Urine Routine)', 'price' => 25],
            ['code' => 'T1588', 'name' => 'Urobilinogen (Random Urine)', 'price' => 30],
            ['code' => 'T1393', 'name' => 'Valproic Acid (Depakin Level)', 'price' => 100],
            ['code' => 'T1568', 'name' => 'Varicella Zoster Antibodies,  IgG', 'price' => 105],
            ['code' => 'T2598', 'name' => 'Varicella Zoster Antibodies,  IgM', 'price' => 105],
            ['code' => 'T1069', 'name' => 'Vitamin B12', 'price' => 85],
            ['code' => 'T1332', 'name' => 'Vitamin D Total', 'price' => 165],
            ['code' => 'T1577', 'name' => 'Zinc', 'price' => 85],
        ];

        foreach ($biomarkers as $index => $data) {
            $slug = 'biomarker-' . strtolower($data['code']) . '-' . ($index + 1);
            $service = Service::firstOrNew(['slug' => $slug]);
            if (! $service->exists) {
                $service->id = SequentialId::next(Service::class, 'srv');
            }

            $service->fill([
                'title' => $data['name'],
                'slug' => $slug,
                'category' => 'lab-tests',
                'subcategory' => 'customize-lab-package',
                'status' => 'active',
                'active' => true,
                'price' => $data['price'],
                'original_price' => $data['price'],
                'sale_price' => 0,
                'currency' => 'AED',
                'home_visit_fee_included' => false,
                'duration' => '',
                'estimated_visit_time' => '',
                'image' => '/images/lab-tests/srv-lab-home-lipid-profile.jpg',
                'short_description' => $data['name'],
                'full_description' => $data['name'],
                'description' => $data['name'],
                'inclusions' => [],
                'preparation_instructions' => '',
                'who_is_it_for' => '',
                'service_location' => 'at-home',
                'availability' => '',
                'tags' => ['lab-test', 'biomarker', 'customize-package'],
                'display_priority' => $index + 1,
                'seo_title' => $data['name'] . ' - MedZiva',
                'seo_description' => $data['name'] . ' at home in Dubai',
                'popular' => false,
                'enquiry_only' => false,
                'attributes' => [
                    ['label' => 'Test Code', 'value' => $data['code']],
                ],
                'vendor_prices' => [],
                'booking_notice' => '12 hours prior booking',
                'remarks' => '',
            ]);
            $service->save();

            VendorServiceAssignment::firstOrCreate(
                ['vendor_id' => $demoVendor->id, 'service_id' => $service->id],
                ['id' => SequentialId::next(VendorServiceAssignment::class, 'vsa'), 'enabled' => true]
            );
        }

        $this->command->info('Seeded ' . count($biomarkers) . ' biomarkers.');
    }
}
